cd data
mkdir mega
cd mega
wget https://storage.cmusatyalab.org/mega-nerf-data/building-pixsfm.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/building-pixsfm-grid-8.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/building-pixsfm-8.pt
wget https://storage.cmusatyalab.org/mega-nerf-data/rubble-pixsfm.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/rubble-pixsfm-grid-8.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/rubble-pixsfm-8.pt
wget http://vision.soic.indiana.edu/disco_files/ArtsQuad_dataset.tar
wget https://storage.cmusatyalab.org/mega-nerf-data/quad-pixsfm.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/quad-pixsfm-grid-8.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/quad-pixsfm-8.pt
wget https://storage.cmusatyalab.org/mega-nerf-data/residence-pixsfm.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/residence-pixsfm-grid-8.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/residence-pixsfm-8.pt
wget https://storage.cmusatyalab.org/mega-nerf-data/sci-art-pixsfm.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/sci-art-pixsfm-grid-25.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/sci-art-pixsfm-25-w-512.pt
wget https://storage.cmusatyalab.org/mega-nerf-data/campus-pixsfm.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/campus-pixsfm-grid-8.tgz
wget https://storage.cmusatyalab.org/mega-nerf-data/campus-pixsfm-8.pt
